// ArduinoJson - Version: 5.13.2
#include <ArduinoJson.h>
#include <ArduinoJson.hpp>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "CanSat"
  https://create.arduino.cc/cloud/things/f8f73318-477e-4204-a100-5597f414c2e2 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float hum;
  float temp;
  float x;
  float y;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <SoftwareSerial.h>

SoftwareSerial nodemcu(D6, D5);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
   nodemcu.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  StaticJsonBuffer<1000> jsonBuffer;
  JsonObject& data = jsonBuffer.parseObject(nodemcu);
  temp= data["temperature"];
  hum=data["humidity"];
   x = data["x-axis"];
   y = data["y-axis"]; 
}

 
